version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: springCloudDemo
    volumes:
      # Activate to persiste data after docker restart
      - ./data:/data/db
      - ./initdb.d/:/docker-entrypoint-initdb.d/
  mysql:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # Activate to persiste data after docker restart
      - ./data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
  orderservice:
    image : order_service
    restart : always
    ports:
      - "8081:8081"
  carservice:
    image: car_service
    restart: always
    ports:
      - "8080:8080"

networks:
 default:
   name: my_network
